services:
  web:
    build: .
    container_name: django_to_prod_1
    ports:
      - "8000:8000"
    env_file:
      - .env
    # volumes:
    #   - .:/app
    command: > 
      gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 90 --log-level debug django_to_prod_1.wsgi:application
